import numpy as np
import numpy.typing as npt

class EntropyHubCore:
    x: float
    y: float
    z: float

    def __init__(
        self, x: float, y: float, z: float, a: float, b: float, c: float, dt: float
    ) -> None: ...
    @staticmethod
    def from_os_entropy(dt: float) -> "EntropyHubCore": ...
    def reseed_from_os_entropy(self) -> None: ...
    def reseed_rust(self, new_x: float, new_y: float, new_z: float) -> None: ...
    def decide_rust(self, iterations: int) -> int: ...
    def get_trajectory_rust(self, steps: int) -> npt.NDArray[np.float64]: ...
    def estimate_lyapunov_rust(self, total_steps: int, renorm_every: int) -> float: ...
